### ISSUE TITLE
Set-ActionOutput not setting any output

### ISSUE THREAD

**Issue by cherryleafroad** [Amadevus/pwsh-script#11]
Hi,

The `Set-ActionOutput` cmdlet seems to not be working for me at all. I have this workflow, and when it gets to the next step the output isn't even there.

```yaml
name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: test
        uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Set-ActionOutput testout igottest

      - name: Run a multi-line script
        run: |
          echo "${{ steps.test.outputs.testout }}"
```

Thanks for the github action by the way, it's really cool to be able to have all these integrations from within powershell 😄
