### ISSUE TITLE
Action not finishing

### ISSUE THREAD

**Issue by stefankip** [Amadevus/pwsh-script#3]
Hi! First of all thanks for sharing this action!
I'm calling a powershell script like this:
```
- name: Deploy to Umbraco Cloud
  uses: Amadevus/pwsh-script@v1.0.0
  env:
    GIT_ADDRESS: ${{ secrets.GIT_ADDRESS }}
    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
    GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  with:
    script: . ".\$env:DEPLOY_SCRIPT" -cloneurl "$env:GIT_ADDRESS" -uaasuser "$env:GIT_USERNAME" -password "$env:GIT_PASSWORD" -sourcepath "$env:PUBLISH_DIR" -destinationpath "$env:CLONE_DIR"
```

The script is running fine, these are the final lines in [the script](https://github.com/umbraco/vsts-uaas-deploy-task/blob/master/Tasks/DeployUmbracoCloudRepository/DeployToUmbracoCloud.ps1):
```
Write-Host "Deployment finished"

Write-Verbose "Leaving script DeployToUmbracoCloud.ps1"
```

I can see the *Deployment finished* echo in the logs, but the action isn't finishing, it keeps running forever.
How can I make sure the process finished?
