### ISSUE TITLE
Can I execute a script file and specify a working directory?

### ISSUE THREAD

**Issue by staneee** [Amadevus/pwsh-script#7]
Similar to Azure DevOps:

![image](https://user-images.githubusercontent.com/26987099/95829041-4fb5b380-0d68-11eb-928f-daa58a280681.png)

**Comment by amis92** [comment]
Hi, I mean it's not much (any?) different than just doing:

```yml
uses: Amadevus/pwsh-script@v2
with:
  script: Set-Location ./nupkg; ./pack.ps1
```

I considered adding a working directory input, but since it's an additional line anyway, it doesn't differ much with just calling `Set-Location`, unless I'm missing something?
